services:
  - type: web
    name: apex-tss-bot
    runtime: python
    buildCommand: pip install -r requirements_render.txt
    startCommand: python webhook_server.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: 8317486741:AAGvBTv-Id5Qr48JBaq-RXyUAGZQfw7Z5dE
      - key: CHAT_ID
        value: "5484281251"
      - key: WEBHOOK_URL
        value: "https://apex-tss.onrender.com"
      - key: PORT
        value: "10000"
      - key: FDORG_TOKEN
        value: b8b980d46849a1fc55c8bd271bcad18c
    healthCheckPath: /health
    autoDeploy: true   # Auto-deploy on every GitHub push
